### PR TITLE
Update peach.json

### PR DESCRIPTION
**Pull request by TakiShiwa**
Screenshot_2023-07-24-22-53-29-89_ce48f3669154ad2f53ee7715a6cfbfc3

Fixed your activity card

### CODE REVIEW

**Comment by riichimaru** [comment]
i'll have to fix it for all flavours, but thx for pr tho!! ❤️

**Comment by TakiShiwa** [comment]
> i'll have to fix it for all flavours, but thx for pr tho!! ❤️

You're welcome

**Comment by TakiShiwa** [comment]
Also do not remember to remove the comment ( // ) from the code before merging

**Comment by TakiShiwa** [comment]
I removed that 
and fixed this
Screenshot_2023-07-24-23-16-08-62_ce48f3669154ad2f53ee7715a6cfbfc3

**Pull request closed without merging**
